<h4>Frequently Asked Questions</h4>
<div id="faq-links">
	<p>
		<a href="#faq1">What is a DuPont™ StormRoom™ with KEVLAR®?</a>
	</p>
	<p>	
		<a href="#faq2">What is DuPont™ KEVLAR® Brand Aramid Fiber?</a>
	</p>
	<p>
		<a href="#faq3">Who sets the criteria for an aboveground storm shelter?</a>
	</p>
	<p>
		<a href="#faq4">How was the DuPont™ StormRoom™ with KEVLAR® tested?</a>
	</p>
	<p>
		<a href="#faq5">How does the DuPont™ StormRoom™ with KEVLAR® protect me against the forces of tornados or hurricanes?</a>
	</p>
	<p>
		<a href="#faq6">What does a DuPont™ StormRoom™ with KEVLAR® look like within a residential home?</a>
	</p>
	<p>
		<a href="#faq7">What type of homes can have a DuPont™ StormRoom™ with KEVLAR®?</a>
	</p>
	<p>
		<a href="#faq8">Where can the room be located in a residential home?</a>
	</p>
	<p>
		<a href="#faq9">How is the DuPont™ StormRoom™ with KEVLAR® attached to the concrete foundation?</a>
	</p>
	<p>
		<a href="#faq10">Who installs the DuPont™ StormRoom™ with KEVLAR®?</a>
	</p>
	<p>
		<a href="#faq11">How long does it take to install DuPont™ StormRoom™ with KEVLAR®?</a>
	</p>
	<p>
		<a href="#faq12">What will the DuPont™ StormRoom™ with KEVLAR® look like once it is installed?</a>
	</p>
	<p>
		<a href="#faq13">Does the installer finish the DuPont™ StormRoom™ with KEVLAR®?</a>
	</p>
	<p>
		<a href="#faq14">Is the DuPont™ StormRoom™ with KEVLAR® wheelchair accessible?</a>
	</p>	
	<p>
		<a href="#faq15">Does the DuPont™ StormRoom™ with KEVLAR® have ventilation?</a>
	</p>
	<p>
		<a href="#faq16">Can the DuPont™ StormRoom™ with KEVLAR® be used for other applications?</a>
	</p>
	<p>
		<a href="#faq17">What makes the DuPont™ StormRoom™ with KEVLAR® a superior storm shelter?</a>
	</p>
	<p>
		<a href="#faq18">How much will the DuPont™ StormRoom™ with KEVLAR® cost?</a>
	</p>
	<p>
		<a href="#faq19">What about flooding and DuPont™ StormRoom™ with KEVLAR®? </a>
	</p>
</div>

<h6 id="faq1">What is a DuPont™ StormRoom™ with KEVLAR®?</h6>
<p>
	DuPont™ StormRoom™ with KEVLAR® is an in-home aboveground hurricane and tornado shelter. The room is an innovative design created by DuPont engineers using DuPont™ KEVLAR® aramid brand fiber - this is similar material used by law enforcement and military personnel.  The room consists of wall panels containing DuPont™ KEVLAR® material that are connected together using structural steel connectors and are attached to a concrete slab foundation with an epoxy anchoring system. An attractive steel door that meets FEMA requirements is used for the entryway.
</p>
<h6 id="faq2">What is DuPont™ KEVLAR® Brand Aramid Fiber?</h6>
<p>
	DuPont™ Kevlar® brand aramid fiber was invented by DuPont scientists in 1965, and its uses have evolved over the past four decades.  It’s the fiber used in bullet-resistant vests and helmets worn by police and military forces, and is the fiber used in cars for lightweight, durable body sections that withstand impacts during collisions.
</p>
<h6 id="faq3">Who sets the criteria for an aboveground storm shelter?</h6>
<p>
	FEMA (Federal Emergency Management Agency) has created a national standard and published a prescriptive standard in ‘FEMA 320: Taking Shelter from the Storm.’ The current standard requires structures to withstand high wind loads and to resist a 12ft, 15lb, 2’x4’ building timber shot at the shelter at 100 mph. 100mph is how fast a 250+mph wind will carry the 2’x4’. The FEMA criteria were established in conjunction with the national experts on extreme winds from Texas Technical University’s School of Wind Engineering. In addition, the International Code Council has published the ICC-500 Standard for the Design and Construction of Storm Shelters.  The DuPont™ StormRoom™ with KEVLAR® meets the national requirements for hurricane and tornado shelters.
</p>
<h6 id="faq4">How was the DuPont™ StormRoom™ with KEVLAR® tested?</h6>
<p>
	In addition to the Texas Tech testing, the DuPont™ StormRoom™ with KEVLAR® has been tested at three independent labs. The wall panels and the entire room have been tested at these facilities and have been found to meet the national requirements for aboveground storm shelters.
</p>
<h6 id="faq5">How does the DuPont™ StormRoom™ with KEVLAR® protect me against the forces of tornados and hurricanes?</h6>
<p>
	The DuPont™ StormRoom™ with KEVLAR® protects you in three very important ways.  (1) The design of the wall and ceiling panels, which utilize DuPont™ KEVLAR® fiber, prevent flying debris from penetrating into the shelter.  Most deaths and injuries during a tornado are caused by flying debris.  (2) The design of the anchoring system and connecting system prevent wind uplift, even in the extreme winds generated by an EF5 tornado. (3) The design of the wall and ceiling panels and their connection systems are extremely resistant to crushing.  The roof of the StormRoom™ can support over 70,000 pounds, the weight of a loaded tractor-trailer truck.  It is not intended to protect against floods or strom surges that may accompany these storms.  It is not fire resistant.
</p>
<h6 id="faq6">What does a DuPont™ StormRoom™ with KEVLAR® look like within a residential home?</h6>
<p>
	Because DuPont™ StormRoom™ with Kevlar® can be finished inside and out to match the walls in the home.  You or your builder can make it a fully functional room that fits into your everyday life. It can work as a closet, bathroom,  laundry room, or any windowless room in your home. The room can be wired for electricity, set up with plumbing, attached to your home’s air conditioning system, and it is easily finished with furring strips and drywall.  DuPont™ StormRoom™ with KEVLAR® can be installed in your new or existing home.
</p>
<h6 id="faq7">What type of homes can have a DuPont™ StormRoom™ with KEVLAR®?</h6>
<p>
	The DuPont™ StormRoom™ with KEVLAR® is ideal for existing or new residential construction on a concrete slab foundation that meets the design requirements found in FEMA 320. Any engineered foundation that meets the uplift requirements such as those detailed in FEMA 320 would be appropriate for use with this shelter. The room is available in several rectangular configurations with the maximum external footprint equaling 169 square feet. Custom rectangular sizes are available between 16 square feet and 169 square feet.
</p>
<h6 id="faq8">Where can the DuPont™ StormRoom™ with KEVLAR® be located?</h6>
<p>
	DuPont™ StormRoom™ with KEVLAR® must be anchored to a concrete foundation either on the ground floor, in the basement or in a garage.  If the StormRoom™  is being installed for hurricane protection it cannot be installed in the basement or below ground due to flooding issues.
</p>
<h6 id="faq9">How is the DuPont™ StormRoom™ with KEVLAR® attached to the concrete foundation?</h6>
<p>
	The Simpson Strong-Tie Anchor System® and Simpson Epoxy-Tie® Anchoring Adhesives are used to attach the steel tracks of the DuPont™ StormRoom™ with KEVLAR® to your concrete foundation.  A thickened footing is not required, just a standard 4” minimum thickness slab with minimum 3,000 psi reinforced concrete (for optimum performance, the minimum concrete slab size should be reinforced with Steel Welded Wire Mesh).  Our certified installers drill and thoroughly clean each hole before inserting the epoxy and anchor bolts.  This anchoring system has been extensively tested by DuPont engineers and independent laboratories and has been proven to exceed FEMA requirements for anchoring storm shelters.
</p>
<h6 id="faq10">Who installs the DuPont™ StormRoom™ with KEVLAR®?</h6>
<p>
	Only trained and certified installers are authorized to install the DuPont™ StormRoom™ with KEVLAR®. Installation costs are included in the purchase price.
</p>
<h6 id="faq11">How long does it take to Install a DuPont™ StormRoom™ with KEVLAR®?</h6>
<p>
	In most cases, the DuPont™ StormRoom™ with KEVLAR® can be installed in a new or existing construction in a single day.  When the installation team has finished tightening the last bolt, the DuPont™ StormRoom™ with KEVLAR® is ready to be used to protect you and your family against the strongest of storms.
</p>
<h6 id="faq12">What will the DuPont™ StormRoom™ with KEVLAR® look like once it is installed?</h6>
<p>
	The interior and exterior surfaces of the DuPont™ StormRoom™ with KEVLAR® wall panels are plywood.  The connecting tracks are steel, and the walls and tracks are connected together with bolts.  At the end of the installation, you will see these components.  Once the installation is complete, it is ready for the homeowner or contractor to finish it out as they desire.
</p>
<h6 id="faq13">Does the installer finish the DuPont™ StormRoom™ with KEVLAR®?</h6>
<p>
	No, it is the responsibility of either the homeowner or their contractor to finish the room.  The installers can provide helpful information about how to wire it, drywall it, etc.  In addition, written information on finishing tips is available to the owners and their contractors.
</p>
<h6 id="faq14">Is the DuPont™ StormRoom™ with KEVLAR® wheelchair accessible?</h6>
<p>
	The DuPont™ StormRoom™ with KEVLAR® has no threshold; thus, there is no impediment to a wheelchair.  The standard door size is 2’8” wide, which is passable for most wheelchairs and a 3’ wide door is available if needed.  Also, the latching mechanism for the door all takes place at the lever door handle – a quarter turn of the lever engages six one-inch hardened steel pins into the steel frame of the door, securing the occupants against the high winds of a tornado or hurricane.
</p>
<h6 id="faq15">Does the DuPont™ StormRoom™ with KEVLAR® have ventilation?</h6>
<p>
	Yes. FEMA requires all storm shelters to have ventilation.  The DuPont™ StormRoom™ with KEVLAR® has shielded vents in the ceiling and the door is raised ¾” off the floor, allowing air to flow in and out.  The number of ceiling vents varies depending in the size of the shelter and its recommended occupancy rating.
</p>
<h6 id="faq16">Can the DuPont™ StormRoom™ with KEVLAR® be used for other applications?</h6>
<p>
	Yes. The DuPont™ StormRoom™ with KEVLAR® has a security door option that is intruder resistant, allowing it to be used as a safe place for storage of valuables, sensitive records, etc.  However the StormRoom™ is designed to be a storm shelter and not a "safe room" or "panic room".
</p>
<h6 id="faq17">What makes the DuPont™ StormRoom™ with KEVLAR® a superior storm shelter?</h6>
<p>
	We believe the DuPont™ StormRoom™ with KEVLAR® to be one of the top storm shelters on the market today.  As an above-ground in-home shelter, you don’t have to leave your house and go out into the rain, hail, wind or lightning to reach safety.  The ease of finish-out allows the room to be made into a useful space year-round, such as a closet, bathroom, laundry room, pantry, office, media room, etc.  Unlike all-steel shelters or thick concrete walls, the DuPont™ StormRoom™ with KEVLAR® does not interfere with your cell phone, wi-fi, and radio reception, allowing you to keep in contact with your loved ones, follow the storm’s track, and listen to emergency broadcasts from inside the shelter.  The door opens to the interior of the shelter, so if debris falls against the outside of the shelter you can open the door when the storm is over.  Perhaps most importantly, the DuPont™ StormRoom™ with KEVLAR® is engineered and designed by DuPont, one of the world’s leading science and engineering companies.
</p>
<h6 id="faq18">How much will the DuPont™ StormRoom™ with KEVLAR® cost?</h6>
<p>
	Even though the DuPont™ StormRoom™ with KEVLAR® is second to none in the features it offers, it is still surprisingly affordable for most people.  Our independent authorized dealers set retail pricing, but national pricing surveys have shown that the cost to the consumer starts at under $6,000 and up.  The cost increases depending on the size of the shelter, options chosen, and whether the shelter is installed in new construction or is being retrofitted into an existing home.
</p>
<h6 id="faq19">What about flooding and DuPont™ StormRoom™ with KEVLAR®?</h6>
<p>
	DuPont™ StormRoom™ with KEVLAR® is not designed to protect against floodwaters or storm surge.
	The DuPont™ StormRoom™ with KEVLAR® has been designed to protect against flying debris, wind uplift, and crushing forces that extreme weather can cause. 
</p>
