		<h4>Proven by Science</h4>
		<p class="grid_10 alpha beta">
			The building science experts at DuPont have revolutionized severe weather protection for the home with the DuPont™ StormRoom™, 
			the  only in-home hurricane and tornado shelter reinforced with DuPont™ KEVLAR®. These specially reinforced walls form 
			a virtually impenetrable barrier to protect families from flying debris during a tornado or a hurricane.
			<br />
			<br />
			The DuPont™ StormRoom™ is specially designed to endure wind speeds of up to 250 miles per hour. Independent impact 
			tests show that the DuPont™ StormRoom™ withstood repeated hits by building timbers fired at speeds equivalent to those 
			experienced in Category 5 hurricanes and F5 tornados.  
			
			<br />
			<br />
			There’s also the added comfort of knowing that the DuPont™ StormRoom™ is solidly anchored to concrete foundations with chemically-set anchors strong enough to help resist the wind uplift generated by the most powerful storms.

		</p>
		<p class="grid_4 alpha beta">
			<img src="<?php echo site_url('images/flying_board.jpg');?>" class="image-padding-left" id="flying_board" alt="Flying Board Test"/>
		</p>
		<p class="grid_4 alpha beta">	
			<img src="<?php echo site_url('images/flying_board2.jpg');?>" class="image-padding-left" id="flying_board2" alt="Flying Board Close-Up"/>
		</p>
